### ISSUE TITLE
Unclear how to change typographic scale

### ISSUE THREAD

**Issue by seadowg** [seadowg/collect-design#1]
This came about from a discussion on potentially bumping up the size of the "heading" (`Subtitle 1` style) in 1 and 2 line lists as the text looks pretty small on tablets. 

It might be useful in future to change individual style within the Typographic Scale that the Material Design Editor generates for us. Within the tool (Sketch plugin) we seem to be able to change the font itself and this adjusts the sizes to accomodate that font but if we wanted to bump up the size of `Subtitle 1` for instance I'm not sure how we could do that.

This could just be a limitation in the tooling or potentially an opinionated choice from Google. If it's not possible for either reason it probably makes sense to have any deviations just be defined in code as "special cases".

@jbroring do you have any thoughts on this?

**Comment by jbroring** [comment]
I haven't seen the size on a tablet, however bumping the size of a subtitle could (visually) work. It is common to have multiple sizes of heading (h1, h2, h3, etc), different sizes of subtitles isn't that common but I don't see problems against it.

What you could look at is what is the ratio of the Body & the Subtitle style and figure out if you can create something looking nice taking that ratio into account and applying it to the Heading above to figure out the size of the Subtitle.

For instance:
`Body = 16`
`Subtitle = 20`
`Ratio = 1.25 / 80%`
`Body * 1.25 (Ratio) = 20 (Subtitle)`
`Subtitle * 0.80 (Ratio) = 16 (Body)`

Example: 
`Heading = 32`
`NewSubtitle = Heading * Ratio`

The NewSubtitle is then the size of 25.6, which you should probably adjust to 26 because that is nice and rounded. 

That might be one theory of how you might look at introducing a different size.

**Comment by seadowg** [comment]
@jbroring that makes sense. I'm guessing you also don't think there is a way to add/change text styles in the Material Editor?

**Comment by seadowg** [comment]
I chatted to the team at Android Dev Summit and they agreed that [adding a new style would be the way to go](https://www.notion.so/Questions-asked-c1678cddecad46b48f9d632e25922beb).
